apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadqivc4929-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadqivc4929-tenant-component
    app.kubernetes.io/part-of: loadqivc4929-tenant-app
  name: loadqivc4929-tenant-component
  namespace: loadqivc4929-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadqivc4929-tenant-component
status:
  loadBalancer: {}
